CREATE TABLE DECKS(
	NAME VARCHAR(256) PRIMARY KEY
);

CREATE TABLE CARDS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TYPE VARCHAR(30),
	CONTENT BLOB,
	DECK_NAME VARCHAR(256),
	FOREIGN KEY(DECK_NAME) REFERENCES DECKS(NAME)
);


CREATE TABLE ANSWERS(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	A_TEXT TEXT,
	CARD_ID INTEGER,
	FOREIGN KEY(CARD_ID) REFERENCES CARDS(ID)
);
