<CustomModal2>:
    background: ''
    size_hint: .8 , None
    height: 0
    pos_hint: {'left': 0 , 'top': .685}
    background_color: 0,0,0,.1
    ScrollView
        GridLayout:
            canvas:
                Color:
                    rgba: 0,0,0,1
                Rectangle
                    pos: self.pos
                    size: self.size
            id: gl1
            spacing: '1dp' 
            size_hint_y: None
            height: 0
            cols: 1
